function(target_warnings TARGET)
    if(MSVC)
        target_compile_options(${TARGET} PRIVATE /W4 /sdl /permissive-)
    else()
        target_compile_options(${TARGET} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wshadow)
    endif()
endfunction()